### ISSUE TITLE
Fix lint warnings

### ISSUE THREAD

**Issue by yosriady** [comit-network/ambrosia#7]
**Overview**

Run `yarn lint` and `yarn tsc`. 
You should see some lint / typescript warnings. Fix them until the warnings go away.

Fixing some (you don't have to fix all of them) of these issues should give you an opportunity to get an overview of the project.

**TODOs**

- [ ] Set up and run the app locally https://github.com/comit-network/taker-ui#prerequisites
- [ ] `yarn lint`
- [ ] `yarn tsc`
- [ ] Resolve the lint warnings (as much as you can)
- [ ] Open a PR

**Comment by da-kami** [comment]
outdated
